# Generated by Django 5.1.6 on 2025-04-16 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Visitor", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="senior_manager_name",
        ),
        migrations.RemoveField(
            model_name="directorate",
            name="director_name",
        ),
        migrations.AddField(
            model_name="department",
            name="senior_manager",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="senior_manager_of",
                to="Visitor.employee",
            ),
        ),
        migrations.AddField(
            model_name="directorate",
            name="director",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="director_of",
                to="Visitor.employee",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="directorate",
            field=models.ForeignKey(
                default=12,
                on_delete=django.db.models.deletion.CASCADE,
                to="Visitor.directorate",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employee",
            name="designation",
            field=models.CharField(
                choices=[
                    ("Director", "Director"),
                    ("Senior Manager", "Senior Manager"),
                    ("Junior Manager", "Junior Manager"),
                    ("Officer", "Officer"),
                    ("Staff", "Staff"),
                    ("Intern", "Intern"),
                    ("Attachee", "Attachee"),
                ],
                max_length=50,
            ),
        ),
    ]
