# Generated by Django 5.1.6 on 2025-04-16 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Visitor", "0002_remove_department_senior_manager_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="directorate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Visitor.directorate",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Visitor.department",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="designation",
            field=models.CharField(
                choices=[
                    ("Director", "Director"),
                    ("Senior Manager", "Senior Manager"),
                    ("Junior Manager", "Junior Manager"),
                    ("Employee", "Employee"),
                    ("Attachee", "Attachee"),
                ],
                max_length=50,
            ),
        ),
    ]
